# Generated by Django 5.2.17 on 2026-08-30 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0002_category_hero_description_category_hero_subtitle_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "content categories",
                "ordering": ("display_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="ContentPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("training", "Training"),
                            ("news", "News"),
                            ("blog", "Blog"),
                        ],
                        max_length=12,
                    ),
                ),
                ("title", models.CharField(max_length=220)),
                ("slug", models.SlugField(unique=True)),
                ("excerpt", models.TextField()),
                ("content", models.TextField()),
                ("featured_image", models.ImageField(blank=True, upload_to="content/")),
                ("author_name", models.CharField(default="DICHO Ltd", max_length=120)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                ("published_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.CharField(blank=True, max_length=320)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posts",
                        to="content.contentcategory",
                    ),
                ),
                (
                    "related_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_posts",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ("-published_at", "-created_at"),
            },
        ),
    ]
