# Generated by Django 5.2.17 on 2026-08-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order", "question"],
            },
        ),
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(default="DICHO Ltd", max_length=100)),
                (
                    "tagline",
                    models.CharField(
                        default="Natural • Quality • Trusted", max_length=150
                    ),
                ),
                ("phone", models.CharField(default="0788428711 / 0783285278", max_length=50)),
                ("email", models.EmailField(default="info@dicho.rw", max_length=254)),
                (
                    "whatsapp_number",
                    models.CharField(default="0788428711", max_length=30),
                ),
                ("address", models.CharField(default="Huye, Rwanda", max_length=255)),
                (
                    "working_hours",
                    models.CharField(
                        default="Mon - Sat: 8:00 AM - 6:00 PM", max_length=255
                    ),
                ),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("whatsapp_url", models.URLField(blank=True, default="https://wa.me/250788428711")),
                ("logo", models.ImageField(blank=True, upload_to="site/")),
                ("favicon", models.ImageField(blank=True, upload_to="site/")),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("message", models.TextField()),
                ("rating", models.PositiveSmallIntegerField(default=5)),
                ("image", models.ImageField(blank=True, upload_to="testimonials/")),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
    ]
