# Generated by Django 5.2.17 on 2026-08-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="linkedin_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="tiktok_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="x_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="youtube_url",
            field=models.URLField(blank=True),
        ),
    ]
