# Generated by Django 5.2.17 on 2026-08-28 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("image", models.ImageField(blank=True, upload_to="categories/")),
                (
                    "asset_path",
                    models.CharField(
                        blank=True,
                        help_text="Optional existing static image path",
                        max_length=255,
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(blank=True, default="bi bi-leaf", max_length=80),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("slug", models.SlugField(unique=True)),
                ("short_description", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("benefits", models.TextField(blank=True)),
                ("ingredients", models.TextField(blank=True)),
                ("usage_instruction", models.TextField(blank=True)),
                ("size", models.CharField(max_length=60)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="products/")),
                (
                    "asset_path",
                    models.CharField(
                        blank=True,
                        help_text="Optional existing static image path",
                        max_length=255,
                    ),
                ),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_best_seller", models.BooleanField(default=False)),
                ("is_new", models.BooleanField(default=False)),
                ("is_on_sale", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="products/gallery/")),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_images",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
    ]
