# Generated by Django 5.2.17 on 2026-08-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="hero_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="category",
            name="hero_subtitle",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="category",
            name="hero_title",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="category",
            name="show_in_hero",
            field=models.BooleanField(default=False),
        ),
    ]
